#!/bin/bash

SYSTEMCTL="`which systemctl`"
CHKCONFIG="`which chkconfig`"

if test -x $SYSTEMCTL; then
    cp /opt/OrangeAssassin/orangeassassin.service /lib/systemd/system/
    $SYSTEMCTL daemon-reload
    $SYSTEMCTL enable orangeassassin
    $SYSTEMCTL start orangeassassin
elif test -x $CHKCONFIG; then
    cp /opt/OrangeAssassin/orangeassassin-init.d /etc/init.d/orangeassassin
    chmod 755 /etc/init.d/orangeassassin
    $CHKCONFIG --level 2345 orangeassassin on
else
    echo "Warning: Unable to activate service orangeassassin as neither systemctl or chkconfig executables found."
fi
echo 'SAUPDATE=yes' >>/etc/sysconfig/sa-update
